channels:
  -
    id: purgers
    grants:
      - 0
      - 2
      - 3
  -
    id: queue
    grants:
      - 0
      - 2
      - 3
  -
    id: diagnostics
    grants:
      - 3
  -
    id: purger_dropsolid_purge_ef0fcb369e
    grants:
      - 0
      - 2
      - 3
