name: Configuration Rewrite
type: module
description: Rewrites existing configuration on module installation via using a "rewrite" folder in the config directory.
php: 7.1
core_version_requirement: ^8.7.7 || ^9
package: Configuration

# Information added by Drupal.org packaging script on 2021-01-27
version: '8.x-1.4'
project: 'config_rewrite'
datestamp: 1611769144
