<?php

/**
 * @file
 * Custom hooks and functions for module.
 */

use Drupal\custom_events\Event\CustomEventsPreprocessEvent;

/**
 * Implements hook_preprocess_HOOK().
 */
function custom_events_preprocess_html(&$variables) {
  /** @var \Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher $dispatcher */
  $dispatcher = \Drupal::service('event_dispatcher');
  // Create event object passing arguments.
  $event = new CustomEventsPreprocessEvent($variables);
  // Call it.
  $dispatcher->dispatch((object) CustomEventsPreprocessEvent::PREPROCESS_HTML, $event);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function custom_events_preprocess_page(&$variables) {
  /** @var \Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher $dispatcher */
  $dispatcher = \Drupal::service('event_dispatcher');
  // Create event object passing arguments.
  $event = new CustomEventsPreprocessEvent($variables);
  // Call it.
  $dispatcher->dispatch((object) CustomEventsPreprocessEvent::PREPROCESS_PAGE, $event);
}
