<?php

/**
 * @file
 * Hook implementations for the Field Limiter module.
 */

/**
 * Implements hook_field_formatter_info_alter().
 */
function field_limiter_field_formatter_info_alter(array &$info) {
  /** @var \Drupal\Core\Field\FieldTypePluginManagerInterface $field_type_manager */
  $field_type_manager = \Drupal::service('plugin.manager.field.field_type');
  $field_types = array_keys($field_type_manager->getDefinitions());

  $info['field_limiter']['field_types'] = $field_types;
}
