# Add some custom theme settings
rocketship_theme_demo.settings:
  type: theme_settings
  label: 'Rocketship Demo theme settings'
  mapping:
    header_fixed:
      type: boolean
      label: 'Fixed header'
    language_dropdown:
      type: boolean
      label: 'Language dropdown'
    language_abbr:
      type: boolean
      label: 'Language abbreviations'
    scroll_to:
      type: boolean
      label: 'Animated anchor scrolling'
    scroll_to_exceptions:
      type: textfield
      label: 'Exceptions'
    lazy_loading_fallback:
      type: boolean
      label: 'Make lazy loading work on browsers with non-native support'
