config_import_locale.settings:
  title: 'Config import settings'
  route_name: config_import_locale.settings
  description: 'Configure the behaviour of interface translations on config import'
  parent: locale.translate_page
  weight: 25